name: "New Job Listing"
description: "Submit a new job listing to be added to the website"
title: "New Job: [Job Title]"
labels: ["job-listing"]
body:
  - type: input
    id: job_title
    attributes:
      label: "Job Title"
      placeholder: "General Labour"
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: "Job Location"
      placeholder: "Toronto, ON"
    validations:
      required: true

  - type: input
    id: area
    attributes:
      label: "Occupational Area"
      placeholder: "Construction"
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: "Publish Date"
      placeholder: "YYYY-MM-DD"
    validations:
      required: true
