name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Ensures that credentials are reset for deployment
          fetch-depth: 0  # Ensures full Git history is available

      - name: Inject Secret into JSON File
        run: |
          echo '{ "GITHUB_TOKEN": "${{ secrets.GH_PAT }}" }' > secret.json

      - name: Use Secret Without Committing
        run: |
          cp secret.json /tmp/secret.json  # Temporarily store it outside the repo

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: .
          clean: true

      - name: Remove Secret File
        run: rm -f /tmp/secret.json  # Remove it after use
