name: Update Jobs JSON
on:
  issues:
    types: [opened]

jobs:
  update-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug Issue JSON
        run: cat $GITHUB_EVENT_PATH

      - name: Get issue details
        id: issue
        run: |
          BODY=$(jq -r '.issue.body' $GITHUB_EVENT_PATH)

          echo "JOB_TITLE=$(echo "$BODY" | awk -v RS='' '/### Job Title/{getline; print}' | xargs)" >> $GITHUB_ENV
          echo "LOCATION=$(echo "$BODY" | awk -v RS='' '/### Job Location/{getline; print}' | xargs)" >> $GITHUB_ENV
          echo "AREA=$(echo "$BODY" | awk -v RS='' '/### Occupational Area/{getline; print}' | xargs)" >> $GITHUB_ENV
          echo "DATE=$(echo "$BODY" | awk -v RS='' '/### Publish Date/{getline; print}' | xargs)" >> $GITHUB_ENV



      - name: Update jobs.json
        run: |
          jq --arg title "$JOB_TITLE" --arg location "$LOCATION" --arg area "$AREA" --arg date "$DATE" \
          '. + [{"title": $title, "location": $location, "area": $area, "date": $date}]' jobs.json > temp.json && mv temp.json jobs.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add jobs.json
          git commit -m "Added new job: $JOB_TITLE"
          git push
