name: Update Jobs JSON
on:
  issues:
    types: [opened]

jobs:
  update-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
            
      - name: Get issue details
        id: issue
        run: |
          echo "JOB_TITLE=$(jq -r '.issue.title' $GITHUB_EVENT_PATH | sed 's/New Job: //')" >> $GITHUB_ENV
          echo "LOCATION=$(jq -r '.issue.body[] | select(.id == \"location\") | .value' $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
          echo "AREA=$(jq -r '.issue.body[] | select(.id == \"area\") | .value' $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
          echo "DATE=$(jq -r '.issue.body[] | select(.id == \"date\") | .value' $GITHUB_EVENT_PATH)" >> $GITHUB_ENV


      - name: Update jobs.json
        run: |
          jq --arg title "$JOB_TITLE" --arg location "$LOCATION" --arg area "$AREA" --arg date "$DATE" \
          '. + [{"title": $title, "location": $location, "area": $area, "date": $date}]' jobs.json > temp.json && mv temp.json jobs.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add jobs.json
          git commit -m "Added new job: $JOB_TITLE"
          git push
